version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - uploads_data:/var/www/localhost/htdocs/assets/uploads

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - .env

volumes:
  mariadb_data:
  uploads_data:
